### ISSUE TITLE
[Step] Find a Modeler 

### ISSUE THREAD

**Issue by StarterCraft** [StarterCraft/krt0#1]
The first step in the development is finding a team mate with modeling skills. If the step will fail, the project will fail.

**Comment by fsendventd** [comment]
Dude. We here in the MTS community have a motto: "make it yourself." You're not going to be able to find a modeler anywhere if you keep begging for help like you are in the server, and even then I don't think anyone really wants to help because we all have our own projects. Either you make it yourself or you don't make it. It's that simple.

**Comment by TheCactus27** [comment]
Learn to model like everyone else did.

**Comment by DrprofLuigi** [comment]
"I'm going to make a content pack, I'll just need a modeller, a json expert, and a good texture artist."

**Comment by StarterCraft** [comment]
Due to this reaction of the community, I stop servicing this repository and give everyone the right to copy my work that I did for this failed project. Thanks!
